### ISSUE TITLE
Запись в числитель/знаменатель больших чисел приводит к закрытию приложения.

### ISSUE THREAD

**Issue by X-Jedi-Knight-X** [AntipinN/study#3]
1) Запускаем приложение.
2) Начинаем решать любые задачи.
3) Записываем в числитель/знаменатель сколь угодно большие числа.
![image](https://github.com/user-attachments/assets/baa6e0dd-e10c-48cc-80b3-58cd51237ea3)

4) После чего приложение закрывается с кодом 134.
![image](https://github.com/user-attachments/assets/9a6ee0e0-9583-425d-9bf1-3811e1ab4ea0)

Ожидаемое поведение: 
1. Ограничение на максимальное количество цифр, которые можно ввести в поля.
2. Подсчёт заданных пользоватем больших чисел происходит без закрытия приложения.

**Comment by Pantorius** [comment]
Должно быть исправлено в этой версии.
